[workspace]
members = [
    "fortress",
    "fortress_bake",
    "generational_slab",
]

# All dependencies (but not this crate itself or any workspace member)
# will be compiled with -Copt-level=2.
[profile.dev.package."*"]
opt-level = 2

[profile.release]
debug = true