[package]
name = "fortress"
version = "0.1.0"
authors = ["Joseph <wax818@gmail.com>"]
edition = "2018"

[dependencies]
enum-iterator = "0.3"
generational_slab = { path = "../generational_slab"}
gl = "0.12"
glm = "0.2"
hashbrown = "0.2"
lazy_static = "1.3"
memmap = "0.6"
nalgebra = "0.18"
ncollide2d = "0.19"
notify = "4.0"
nphysics2d = "0.11"
png = "0.14"
rand = "0.6"
rand_xorshift = "0.1"
rect_packer = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.sdl2]
version = "0.32"
default-features = false
features = ["mixer"]

[lib]
name = "fortress"
path = "src/lib/lib.rs"

[[bin]]
name = "fortress"
path = "src/bin/main.rs"
