[package]
name = "fortress"
version = "0.1.0"
authors = ["Joseph <wax818@gmail.com>"]

[dependencies]
gl = "0.10"
glm = "0.2"
lazy_static = "1.0"
liquidfun = { path = "../liquidfun" }
lodepng = "2.1"
notify = "4.0"
sdl2 = "0.31"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[lib]
name = "fortress"
path = "src/lib/lib.rs"

[[bin]]
name = "fortress"
path = "src/bin/main.rs"
