[package]
name = "fortress"
version = "0.1.0"
authors = ["Joseph <wax818@gmail.com>"]

[dependencies]
enum-iterator = "0.2"
gl = "0.10"
glm = "0.2"
lazy_static = "1.0"
liquidfun = { path = "../liquidfun" }
lodepng = "2.1"
notify = "4.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
slab = "0.4"

[dependencies.sdl2]
version = "0.31"
default-features = false
features = ["mixer"]

[lib]
name = "fortress"
path = "src/lib/lib.rs"

[[bin]]
name = "fortress"
path = "src/bin/main.rs"
